export const colorThemes = [
  {
    id: 'blue',
    name: 'Ocean Blue',
    primary: '221 83% 53%',
    accent: '221 100% 96%',
  },
  {
    id: 'purple',
    name: 'Royal Purple',
    primary: '270 70% 55%',
    accent: '270 100% 96%',
  },
  {
    id: 'green',
    name: 'Forest Green',
    primary: '142 70% 40%',
    accent: '142 100% 96%',
  },
  {
    id: 'orange',
    name: 'Sunset Orange',
    primary: '24 95% 53%',
    accent: '24 100% 96%',
  },
  {
    id: 'pink',
    name: 'Rose Pink',
    primary: '340 75% 55%',
    accent: '340 100% 96%',
  },
  {
    id: 'teal',
    name: 'Ocean Teal',
    primary: '180 65% 40%',
    accent: '180 100% 96%',
  },
  { id: 'red', name: 'Cherry Red', primary: '0 72% 51%', accent: '0 100% 96%' },
  {
    id: 'indigo',
    name: 'Deep Indigo',
    primary: '240 60% 55%',
    accent: '240 100% 96%',
  },
  {
    id: 'slate',
    name: 'Slate Gray',
    primary: '215 16% 47%',
    accent: '215 16% 96%',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    primary: '160 84% 39%',
    accent: '160 84% 96%',
  },
  {
    id: 'amber',
    name: 'Amber',
    primary: '38 92% 50%',
    accent: '38 92% 96%',
  },
  {
    id: 'crimson',
    name: 'Crimson',
    primary: '348 83% 47%',
    accent: '348 83% 96%',
  },
  {
    id: 'lime',
    name: 'Lime',
    primary: '84 81% 44%',
    accent: '84 81% 96%',
  },
  {
    id: 'cyan',
    name: 'Cyan',
    primary: '190 90% 41%',
    accent: '190 90% 96%',
  },
  {
    id: 'midnight',
    name: 'Midnight',
    primary: '222 47% 11%',
    accent: '222 47% 96%',
  },
]

export const fontFamilies = [
  { id: 'inter', name: 'Inter', value: "'Inter', system-ui, sans-serif" },
  { id: 'outfit', name: 'Outfit', value: "'Outfit', sans-serif" },
  { id: 'roboto', name: 'Roboto', value: "'Roboto', sans-serif" },
  { id: 'open-sans', name: 'Open Sans', value: "'Open Sans', sans-serif" },
  { id: 'montserrat', name: 'Montserrat', value: "'Montserrat', sans-serif" },
  {
    id: 'plus-jakarta',
    name: 'Plus Jakarta Sans',
    value: "'Plus Jakarta Sans', sans-serif",
  },
  { id: 'manrope', name: 'Manrope', value: "'Manrope', sans-serif" },
  {
    id: 'playfair',
    name: 'Playfair Display',
    value: "'Playfair Display', serif",
  },
  { id: 'lora', name: 'Lora', value: "'Lora', serif" },
  { id: 'quicksand', name: 'Quicksand', value: "'Quicksand', sans-serif" },
  {
    id: 'space-grotesk',
    name: 'Space Grotesk',
    value: "'Space Grotesk', sans-serif",
  },
  { id: 'work-sans', name: 'Work Sans', value: "'Work Sans', sans-serif" },
  { id: 'raleway', name: 'Raleway', value: "'Raleway', sans-serif" },
  { id: 'cabin', name: 'Cabin', value: "'Cabin', sans-serif" },
  { id: 'georgia', name: 'Georgia', value: 'Georgia, serif' },
  { id: 'mono', name: 'Monospace', value: 'ui-monospace, monospace' },
  {
    id: 'system',
    name: 'System Default',
    value: 'system-ui, -apple-system, sans-serif',
  },
]
